### ISSUE TITLE
overlapping loop device exists

### ISSUE THREAD

**Issue by konsumer** [ryankurte/docker-rpi-emu#18]
My versions:

```
Linux 5.0.0-15-generic #16pop0-Ubuntu SMP Wed May 15 14:41:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Docker version 18.09.5, build e8ff056
```

I am using [raspbian latest](https://downloads.raspberrypi.org/raspbian_lite_latest) in a makefile that looks like this:

```Makefile
CWD=$(shell pwd)
RUN_ARGS=-it --rm --privileged=true -v $(CWD)/images:/usr/rpi/images -w /usr/rpi ryankurte/docker-rpi-emu
IMAGE=zerostomp.img

# Launch the docker image into an emulated session
emu: images/$(IMAGE)
	@echo "Launching interactive emulated session"
	@docker run $(RUN_ARGS) /bin/bash -c './run.sh images/$(IMAGE)'

# open host in docker
host: images/$(IMAGE)
	@docker run $(RUN_ARGS) /bin/bash

# Expand the image by a specified size
# TODO: implement expand script to detect partition sizes
expand: images/$(IMAGE)
	@echo "Expanding disk by 1G."
	@dd if=/dev/zero bs=1M count=1024 >> images/$(IMAGE)
	@docker run $(RUN_ARGS) ./expand.sh images/$(IMAGE) 1024

# download a zip of current raspbian-lite
images/raspbian_lite.zip:
	@echo "Getting zip of latest raspbian_lite."
	@mkdir images
	@wget https://downloads.raspberrypi.org/raspbian_lite_latest -O images/raspbian_lite.zip

# unzip image to images/$(IMAGE)
images/$(IMAGE): images/raspbian_lite.zip
	@echo "Extracting disk image for raspbian_lite."
	@unzip images/raspbian_lite.zip
	@mv *.img images/$(IMAGE)
```

It can do all the downloading/extracting, etc, but when I try to `make emu` I get this:

```
Extracting disk image for raspbian_lite.
Archive:  images/raspbian_lite.zip
  inflating: 2019-04-08-raspbian-stretch-lite.img  
Launching interactive emulated session
Attempting to mount images/zerostomp.img to /media/rpi
Attached base loopback at: /dev/loop0
Located partitions: p1 (/boot) at 8192 and p2 (/) at 98304
Closed loopback /dev/loop0
mount: /media/rpi/boot: overlapping loop device exists for /usr/rpi/images/zerostomp.img.
make: *** [Makefile:10: emu] Error 32
```

This appears to be related to [this issue](https://www.raspberrypi.org/forums/viewtopic.php?t=190154). If I am understanding the issue correctly, we just need a `sizelimit` on `/boot` in mount.sh:

```
offset=$((8192*512)),sizelimit=$((85405*512))
```

Should I make a PR?

**Comment by konsumer** [comment]
I ran `make host` (from above makefile) and edited the boot-mount line in `mount.sh`:

```
mount $1 -o loop,offset=$(($P1_START*$BLOCK_SIZE)),rw,sizelimit=$((85405*$BLOCK_SIZE)) $2/boot
```

then ran `./run.sh images/zerostomp.img` and got this error:

```
Attempting to mount images/zerostomp.img to /media/rpi
Attached base loopback at: /dev/loop0
Located partitions: p1 (/boot) at 8192 and p2 (/) at 98304
Closed loopback /dev/loop0
Mounted to /media/rpi and /media/rpi/boot
Bootstrapping Qemu
chroot: failed to run command 'bin/bash': Exec format error
```

Do I need to do something differently?

**Comment by ryankurte** [comment]
You shouldn't need to manually specify the partition offset, but, something in [scripts/mount.sh](https://github.com/ryankurte/docker-rpi-emu/blob/master/scripts/mount.sh#L32) probably needs updating for more recent images.

Exec format error might be because you don't have qemu-system-arm installed?

**Comment by konsumer** [comment]
> You shouldn't need to manually specify the partition offset

The offset line is in your mount.sh. I just added `sizelimit`, which is required to not get the `overlapping loop device exists` error in current raspbian, or on my host system (Ubuntu 19.04.) I was just fixing it within the framework of your project, so this will work:

```
docker run -it --rm --privileged=true -v $(pwd)/images:/usr/rpi/images -w /usr/rpi ryankurte/docker-rpi-emu /bin/bash -c './run.sh /usr/rpi/images/zerostomp.img /bin/bash'
Attempting to mount /usr/rpi/images/zerostomp.img to /media/rpi
Attached base loopback at: /dev/loop14
Located partitions: p1 (/boot) at 8192 and p2 (/) at 98304
Closed loopback /dev/loop14
mount: /media/rpi: overlapping loop device exists for /usr/rpi/images/zerostomp.img.
```

You are also doing `losetup` which is what I am doing on [my own stuff](https://github.com/konsumer/zerostomp/blob/master/builder/setup.sh), but I use it directly, instead of using it to gather info for the mount-offsets, and I don't have to worry about the above error, or managing `offset`/`sizelimit`.

> Exec format error might be because you don't have qemu-system-arm installed?

I have it installed, and am using it fine in my project, directly. I think the error comes from the scripts trying to just run a chroot (it's rpi binaries on a x86_64 host, inside a chroot, which seems to need other things to work.)

I moved [my own project](https://github.com/konsumer/zerostomp) to not use docker-rpi-emu, and just do all this stuff directly in qemu, without docker. It's working pretty well for me. The complications of having to maintain a docker container (that only runs on a pi, and needs other things like audio passed through) on top of a light rpi docker host system image I would also have to also maintain started to seem a bit silly compared to just scripting the changes in a running emulator & making my light image file, and installing the changes directly, that I need directly to get my project done.

My overall goal is to get a pizero booted as quickly as possible into a puredata patch, and send it messages from GPIO. I think I'm just about there, but I'd be happy to get it all working better with docker.

While trying to research the issues I was having and get my stuff building well, I realized that recently there has been some work on getting foreign binaries running on docker automatically. This works great for me on linux:

```
sudo apt install -y qemu binfmt-support qemu-user-static
update-binfmts --display
docker run --rm -ti arm32v7/debian:stretch-slim
```

I will probly work on  a light rpi image that just boots right into docker, and I can do my dev on my desktop in docker. It will greatly simplify the whole thing, and I can use it for lots of rpi projects.

**Comment by ryankurte** [comment]
> The offset line is in your mount.sh. I just added sizelimit ...

ahh i misunderstood that, thanks for clarifying / looks like a useful fix!

> The complications of having to maintain a docker container (that only runs on a pi, and needs other things like audio passed through) on top of a light rpi docker host system image I would also have to also maintain started to seem a bit silly compared to just scripting the changes in a running emulator & making my light image file, and installing the changes directly, that I need directly to get my project done.

yeeep, honestly this project is pretty silly, which i did _try_ to make clear from the readme

> Do you too wish you could run Raspberry Pi apps in a docker container against a persistant .img file inside xhyve on macOS? Then this is the project for you!

> It's also not a very good docker container, requiring priveledged mode to mount loopback adaptors and qemu on the docker host. All the scripts here can be run on native linux if you're that way inclined.

the scipts are useful, and hopefully it serves as a functional example, but the docker stuff really only helps with getting the right tools on OSX. i'm glad you've got a good solution / hopefully this helped ^_^

**Comment by konsumer** [comment]
> ahh i misunderstood that, thanks for clarifying / looks like a useful fix!

I will make a PR when I get finished with the current project I am working on.

> yeeep, honestly this project is pretty silly, which i did try to make clear from the readme

No offense, seriously. Your project actually gave me some great ideas.

I did manage to get `binfmt` stuff working really nice with docker under qemu, eventually. I'm probly going to use this for image-building as it really speeds up dev-time. I can compile stuff inside a pi-emulator that boots really fast, and is easy to config via docker. Docker volumes are also much more convenient than qemu's vfat mounts (that corrupt if you edit files on host.) It also seems like it runs faster, for whatever reason, than running an image in qemu, directly. It definitely boots faster.

For this current project, I am leaning more towards scripted building of the img file, instead of docker for the runtime. I still think docker could help with containing all the software and config needed in one place, and it's pretty cool that you can run the app's docker image via `binfmt`, so it might be worth it even if it is a lil extra bother, especially if you don't need to passthrough any hardware like sound.

**Comment by ryankurte** [comment]
solved in https://github.com/ryankurte/docker-rpi-emu/commit/a66a9667bdf0745379e2fbe221ecbed309669441 ^_^

**Comment by konsumer** [comment]
Would you mind publishing this on dockerhub? I went back to trying out docker for building img files, and still get same error. I can use the Dockerfile directly, for now, but it'd be cool to not have to include it in my project (and just reference yours.)

**Comment by konsumer** [comment]
Also, I added PR that will simplify mounting the loops.

**Comment by ryankurte** [comment]
huh, dockerhub auto build seems to have failed in an interesting way, have re-added so hopefully it comes back.

neat! looks like a good simplification, tho, CI doesn't seem to like it?

**Comment by konsumer** [comment]
CI doesn't seem to like #17 either. Not sure. I can investigate more, later. Also, looks like in some situations (for example in testing with mac) docker will need to have volume access to `/dev`, which is maybe not great, even though this is the specific purpose of the `-P` flag for `losetup`.

**Comment by konsumer** [comment]
I'll continue the discussion on the PR.
